 SELECT
    TSIPAR.INTEIRO           AS CODPROD,
    TGFPRO.CODVOL            AS CODVOL,
    TGFPRO.CODLOCALPADRAO    AS CODLOCALORIG,
    nvl (TGFEXC.VLRVENDA, 1) AS VLRUNIT, 
    nvl (TGFEXC.VLRVENDA, 1) AS VLRTOT, 
    1                        AS SEQUENCIA,
    1                        AS QTDNEG

 FROM
    TSIPAR
    INNER JOIN TGFPRO ON TGFPRO.CODPROD = TSIPAR.INTEIRO
     LEFT JOIN TGFEXC ON TGFEXC.CODPROD = TGFPRO.CODPROD

 WHERE
    TSIPAR.CHAVE = 'CODSERVLABM7'
    AND TSIPAR.CODUSU = 0