SELECT
    'SERVICO' AS ORIGEM,
    to_char (INTEIRO) AS INTEIRO
    
FROM
    TSIPAR
    
WHERE
    CHAVE = 'CODSERVLABM7'
    
UNION ALL
    
SELECT
    'FILACAMPO' AS ORIGEM,
    to_char (INTEIRO) AS INTEIRO
    
FROM
    TSIPAR
    
WHERE
    CHAVE = 'CODFILACMPM7'
    
UNION ALL
    
SELECT
    'FILALAB' AS ORIGEM,
    to_char (INTEIRO) AS INTEIRO
    
FROM
    TSIPAR
    
WHERE
    CHAVE = 'CODFILALABM7'
    
UNION ALL
    
SELECT
    'ORCAMENTOTIPO' AS ORIGEM,
    to_char (cab.CODTIPOPER) AS INTEIRO
    
FROM
    TSIPAR par
    INNER JOIN TGFCAB cab ON cab.NUNOTA = par.INTEIRO
    
WHERE
    CHAVE = 'MODCABORCM7'
    
UNION ALL
    
SELECT
    'ORCAMENTONATUREZA' AS ORIGEM,
    to_char (cab.CODNAT) AS INTEIRO
    
FROM
    TSIPAR par
    INNER JOIN TGFCAB cab ON cab.NUNOTA = par.INTEIRO
    
WHERE
    CHAVE = 'MODCABORCM7'
    
UNION ALL
    
SELECT
    'ORCAMENTOVENDA' AS ORIGEM,
    to_char (cab.CODTIPVENDA) AS INTEIRO
    
FROM
    TSIPAR par
    INNER JOIN TGFCAB cab ON cab.NUNOTA = par.INTEIRO
    
WHERE
    CHAVE = 'MODCABORCM7'
    
UNION ALL
    
SELECT
    'ORCAMENTOMOVIMENTO' AS ORIGEM,
    top.TIPMOV AS INTEIRO
    
FROM
    TSIPAR par
    INNER JOIN TGFCAB cab ON cab.NUNOTA = par.INTEIRO
    INNER JOIN TGFTOP top ON top.CODTIPOPER = cab.CODTIPOPER AND top.DHALTER = cab.DHTIPOPER
    
WHERE
    CHAVE = 'MODCABORCM7'
    
UNION ALL
    
SELECT
    'PEDIDOMOVIMENTO' AS ORIGEM,
    top.TIPMOV AS INTEIRO
    
FROM
    TSIPAR par
    INNER JOIN TGFCAB cab ON cab.NUNOTA = par.INTEIRO
    INNER JOIN TGFTOP top ON top.CODTIPOPER = cab.CODTIPOPER AND top.DHALTER = cab.DHTIPOPER
    
WHERE
    CHAVE = 'MODCABPEDM7'
    
UNION ALL
    
SELECT
    'EMPRESA' AS ORIGEM,
    CASE
        WHEN TO_NUMBER (AD_GET_EMPRESATIPOM7 ('S')) < 1 THEN
            '1'
        ELSE
            AD_GET_EMPRESATIPOM7 ('S')
    END AS INTEIRO
    
FROM
    DUAL